### ISSUE TITLE
Tag a new release of this package

### ISSUE THREAD

**Issue by grantlucas** [nesQuick/PHP-Metrics-Client#3]
Is the `v0.1` release still up to date? Could a new release be generated for this package?

It would be great to not have to depend on requiring `dev-master` in my composer file and instead use `~0.1`. The installation can also be updated to just `composer require nesQuick/Metrics`.

I'll be submitting a PR soon with updated README for using `composer require` instead of manually editing `composer.json` so it would be great to have tags to match.

Thanks!

**Comment by grantlucas** [comment]
Also, would you be interested in releasing a v1.0 of this package?

**Comment by grantlucas** [comment]
Another note:

I just tried installing this package, not my fork, and I needed to have `dev-master@dev` for composer to work with my minimum-stability set to stable.

**Comment by OleMchls** [comment]
I think, it would be a good idea to release this as 1.0 now. Because it seems to be kinda stable as it did not need any adjustments in the recent month

**Comment by grantlucas** [comment]
Sounds good to me! I'm going to go ahead and tag the latest master as v1.0.

**Comment by grantlucas** [comment]
:tada: Tagged as v1.0

**Comment by OleMchls** [comment]
:+1: :tada: :sparkling_heart:
